volumes:
  postgres-data:
    external: true

services:
  fastapi:
    environment:
      SIGNING_KEY: 5613d799c5f98ee4de96ce0f4e688432beef7b9081e4edbbfe57ff867a57a6a7
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://faa_user:secret@postgres/faa_db
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  postgres:
      image: postgres:14.5-bullseye
      volumes:
          - postgres-data:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: faa_user
          POSTGRES_DB: faa_db
      ports:
          - 15432:5432
